#Importando as Bibliotecas:

In [130]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as bs

#1ºParte: Coleta de dados e preparação do dataframe:

Interessante notar que cada vez que os comandos abaixo são postos para funcionar, os preços e volumes são constantemente atualizados. Isso gera uma dificuldade, mas também gera uma análise mais precisa que deve considerar a mudança dos preços.

In [118]:
request = requests.get("https://www.coingecko.com/en/nft").text

In [119]:
df = pd.read_html(request)

In [120]:
df1 = df[0]

In [121]:
df1

     #                        NFT  ... 24h Owners Total Assets
0    1                      Azuki  ...      -0.6%      10000.0
1    2                  Cool Pets  ...      95.6%      12345.0
2    3                     CloneX  ...       0.4%      18817.0
3    4       Bored Ape Yacht Club  ...       0.1%      10000.0
4    5      Mutant Ape Yacht Club  ...       0.1%      17940.0
5    6                    Doodles  ...      -0.2%      10000.0
6    7                  Cool Cats  ...      -0.0%       9933.0
7    8                       LAND  ...       0.2%     134981.0
8    9             World of Women  ...       0.2%      10000.0
9   10                Phanta Bear  ...       1.2%      10000.0
10  11                 CyberKongz  ...      -0.1%       5000.0
11  12                 FLUF World  ...       0.0%      10000.0
12  13                 Metroverse  ...       1.0%      10000.0
13  14              Capsule House  ...       0.0%      10000.0
14  15             X Rabbits Club  ...      -0.1%       7502.0
15  16              Boss Beauties  ...      -0.0%      10000.0
16  17            Crypto Unicorns  ...      -7.1%      10000.0
17  18  Decentral Games ICE Poker  ...      -0.4%      14299.0
18  19                PUNKS Comic  ...       0.2%      23204.0
19  20            Adam Bomb Squad  ...       0.0%      24999.0
20  21                 Lazy Lions  ...      -0.1%      10080.0
21  22              OnChainMonkey  ...      -0.1%       9500.0
22  23               Crypto Coven  ...      -0.0%       9757.0
23  24              JRNY NFT Club  ...      -0.1%      10000.0
24  25                   Smilesss  ...       0.1%       8732.0

[25 rows x 10 columns]

- Como eu quero por volta dos últimos 500 NFTs e cada página da coingecko oferece 25 nfts, preciso acessar até a página 20.

In [122]:
dfs = []
for i in range (2, 6):
  request2 = requests.get(f"https://www.coingecko.com/en/nft?page={i}").text
  df = pd.read_html(request2)
  dfs.append(df)

In [123]:
dfs

[[     #                                   NFT  ... 24h Owners Total Assets
  0   26                        The Doge Pound  ...       0.0%      10000.0
  1   27                       the littles nft  ...      -0.4%      10000.0
  2   28          Forgotten Runes Wizards Cult  ...       0.2%       9409.0
  3   29                             Treeverse  ...          ?      20262.0
  4   30                        Creature World  ...      -0.1%      10000.0
  5   31                          loomlock NFT  ...      -0.7%       9546.0
  6   32                          inbetweeners  ...       0.2%      10777.0
  7   33                             CrypToadz  ...       0.1%       7025.0
  8   34                   Global Citizen Club  ...      -1.9%       8888.0
  9   35                                 merge  ...       0.1%      27163.0
  10  36                              MetaHero  ...      -1.9%       6450.0
  11  37                             LilHeroes  ...      -0.1%       7777.0
  12  38                             MekaVerse  ...       0.0%       8888.0
  13  39                              BYOPills  ...      -0.2%      10000.0
  14  40                             Hashmasks  ...       0.0%      16370.0
  15  41                             0N1 Force  ...      -0.2%       7777.0
  16  42                            Lost Poets  ...      -0.1%      27665.0
  17  43                 MoonCats - Acclimated  ...       0.1%      18893.0
  18  44                        FVCK_CRYSTAL//  ...       0.0%       4169.0
  19  45                            VeeFriends  ...       0.0%      10255.0
  20  46              Sneaky Vampire Syndicate  ...      -1.8%       8888.0
  21  47  Jenkins the Valet: The Writer's Room  ...      -0.1%       6942.0
  22  48                         PudgyPenguins  ...      -0.2%       8888.0
  23  49                                 8SIAN  ...       0.1%       8785.0
  24  50                           Satoshibles  ...      -1.0%       5000.0

  [25 rows x 10 columns]],
 [     #                           NFT  ... 24h Owners Total Assets
  0   51          iNFT Personality Pod  ...      -0.3%       9811.0
  1   52                Divine Anarchy  ...      -0.2%      10011.0
  2   53                 Chain Runners  ...      -0.1%      10000.0
  3   54                      BYO Land  ...      -0.0%      10056.0
  4   55                      Animetas  ...      -0.0%      10101.0
  5   56                  The Currency  ...       0.2%       2192.0
  6   57                 Sipherian Inu  ...      -0.1%       9999.0
  7   58                     Anonymice  ...       0.8%      10000.0
  8   59                      Timeless  ...      -0.2%       9421.0
  9   60                    Chibi Apes  ...      -0.1%       3000.0
  10  61              PartyDegenerates  ...      -0.3%      10000.0
  11  62                GenesisApostle  ...       0.2%       7209.0
  12  63                          Loot  ...      -0.0%       7779.0
  13  64                       Blitmap  ...      -0.3%       1700.0
  14  65                      IreneDAO  ...      -0.6%       1106.0
  15  66                  Samurai Saga  ...       0.0%       9999.0
  16  67                  Genesis Mana  ...       0.2%       7591.0
  17  68                 Ethereals WTF  ...       0.1%      12345.0
  18  69  Citizens of Bulliever Island  ...       0.3%      10000.0
  19  70                   Stoner Cats  ...      -0.0%      10419.0
  20  71                   Galaxy Eggs  ...      -0.2%       9999.0
  21  72   Curious Addys' Trading Club  ...       0.5%       5000.0
  22  73                    Lil Pudgys  ...       0.0%      18729.0
  23  74                   CHIBI DINOS  ...      -0.2%      10000.0
  24  75      Purrnelopes Country Club  ...      -0.0%      10000.0

  [25 rows x 10 columns]],
 [      #                               NFT  ... 24h Owners Total Assets
  0    76  CryptoHoots Steampunk Parliament  ...      -0.1%       2500.0
  1    77                       SquidDAONFT  ...       0.0%        131.0
  2    78                           HeadDAO  ...      -0.8%      10000.0
  3    79                    SpacePunksClub  ...      -0.3%       9995.0
  4    80                      Lee Mullican  ...       0.0%         16.0
  5    81                        The Sevens  ...      -0.4%       7000.0
  6    82                       EtherLambos  ...       0.0%       1600.0
  7    83                CryptoZoo Base Egg  ...       0.1%       4160.0
  8    84         Koala Intelligence Agency  ...      -0.0%      10000.0
  9    85                           Feudalz  ...       0.8%       4444.0
  10   86               The Wicked Craniums  ...       0.4%      10762.0
  11   87                          Avastars  ...       0.0%      25450.0
  12   88            Wizards & Dragons Game  ...       0.2%      46169.0
  13   89               Star Sailor Sibings  ...      -0.3%      10100.0
  14   90                        dotdotdots  ...       0.1%       4870.0
  15   91                     Apes of Space  ...       0.1%      10000.0
  16   92                      JunkYardDogs  ...       0.0%       7976.0
  17   93                            Skullx  ...      -0.2%      10000.0
  18   94               Baby Battle Bots G1  ...       0.1%       3498.0
  19   95                    APE DAO REMIX!  ...       0.1%       5550.0
  20   96                 Angry Apes United  ...      -0.1%       8888.0
  21   97               The Vogu Collective  ...       0.1%       7777.0
  22   98                   Bored Ape Comic  ...       0.1%       9999.0
  23   99                        StarryNift  ...       0.0%        142.0
  24  100                    HeavenComputer  ...      -0.0%       7777.0

  [25 rows x 10 columns]],
 [      #                     NFT   Floor Price  ...  Owners  24h Owners Total Assets
  0   101                Metakrew      0.09 ETH  ...  3239.0       -0.1%       7335.0
  1   102    Ready Player Cat NFT       0.1 ETH  ...  2087.0       -0.0%       4950.0
  2   103           Bored Bananas      0.06 ETH  ...  1836.0        0.0%       4027.0
  3   104       Non-Fungible Soup     0.079 ETH  ...  1098.0       -0.1%       2048.0
  4   105        MOONDOGS ODYSSEY      0.02 ETH  ...  1922.0        0.1%       5000.0
  5   106        Generative Masks      0.08 ETH  ...  3465.0        0.0%       9999.0
  6   107             Dope Shibas      0.02 ETH  ...  3977.0        0.0%       9899.0
  7   108           Tools of Rock     0.035 ETH  ...  2278.0        0.0%       7538.0
  8   109              Borpacasso      0.09 ETH  ...  1150.0        0.0%       2250.0
  9   110               Gauntlets     0.088 ETH  ...  3848.0        0.0%      10000.0
  10  111           CryptoZombiez      0.02 ETH  ...   818.0        0.4%       5555.0
  11  112                Template     0.012 ETH  ...  2067.0        0.0%       8992.0
  12  113               Ethermore    0.0289 ETH  ...  2857.0        0.0%      15000.0
  13  114  Extension Loot (xLoot)  0.000001 ETH  ...  2213.0        0.0%       7779.0
  14  115           Space Poggers      0.02 ETH  ...  3442.0        0.0%      12442.0
  15  116      United Punks Union     0.002 ETH  ...  1192.0        0.1%       3624.0
  16  117     Singularity by AIIV     0.099 ETH  ...   523.0        0.0%       1000.0
  17  118             MondrianNFT     0.012 ETH  ...  1836.0        0.0%       4096.0
  18  119         Spirit Orb Pets    0.0585 ETH  ...   370.0        0.0%        777.0
  19  120     Light Super Bunnies    0.0142 ETH  ...  1716.0        0.0%       4457.0
  20  121              Night Kids     0.026 ETH  ...  2191.0        0.0%       5554.0
  21  122                   Bloot     0.035 ETH  ...  3979.0        0.0%       8008.0
  22  123      Dark Super Bunnies    0.0155 ETH  ...  1737.0        0.1%       4409.0
  23  124      AlphaBetty Doodles     0.029 ETH  ...  3470.0        0.0%      10000.0
  24  125                Spookies    0.0148 ETH  ...  2672.0        0.0%       8888.0

  [25 rows x 10 columns]]]

In [124]:
len(dfs)

4

In [125]:
datasets = []
for i in range(len(dfs)):
  datasets.append(dfs[i][0])

In [126]:
len(datasets)

4

In [127]:
df_final = pd.concat([df1, datasets[0], datasets[1], datasets[2], datasets[3]], ignore_index=True)

In [128]:
df_final

       #                    NFT Floor Price  ...   Owners  24h Owners Total Assets
0      1                  Azuki    13.2 ETH  ...   5417.0       -0.6%      10000.0
1      2              Cool Pets    2.27 ETH  ...   7574.0       95.6%      12345.0
2      3                 CloneX    16.0 ETH  ...   8194.0        0.4%      18817.0
3      4   Bored Ape Yacht Club   99.99 ETH  ...   6304.0        0.1%      10000.0
4      5  Mutant Ape Yacht Club   20.69 ETH  ...  11684.0        0.1%      17940.0
..   ...                    ...         ...  ...      ...         ...          ...
120  121             Night Kids   0.026 ETH  ...   2191.0        0.0%       5554.0
121  122                  Bloot   0.035 ETH  ...   3979.0        0.0%       8008.0
122  123     Dark Super Bunnies  0.0155 ETH  ...   1737.0        0.1%       4409.0
123  124     AlphaBetty Doodles   0.029 ETH  ...   3470.0        0.0%      10000.0
124  125               Spookies  0.0148 ETH  ...   2672.0        0.0%       8888.0

[125 rows x 10 columns]

#2ºParte: Limpeza dos dados

In [129]:
df_final.isnull().sum()

#                 0
NFT               0
Floor Price       0
24h               0
7d              125
Market Cap        0
24h Volume        0
Owners            0
24h Owners        0
Total Assets      0
dtype: int64

In [131]:
df_final.drop(columns=["7d", "#"], inplace=True)

In [133]:
df_final.duplicated().sum()

0